### ISSUE TITLE
Double sync of scoped components

### ISSUE THREAD

**Issue by marcinkrawczyk-ef** [sb-mig/sb-mig#96]
version. 2.0.0

For some reason it is trying to double sync scoped components 
```
Components to create after check:
!    web-ui-accordion-item
Trying to create 'web-ui-accordion-item'
!    web-ui-accordion
Trying to create 'web-ui-accordion'
!    web-ui-accordion-item
Trying to create 'web-ui-accordion-item'
!    web-ui-accordion
Trying to create 'web-ui-accordion'
!    web-ui-carousel
Trying to create 'web-ui-carousel'
!    web-ui-carousel
Trying to create 'web-ui-carousel'
!    web-ui-surface
Trying to create 'web-ui-surface'
!    web-ui-surface
Trying to create 'web-ui-surface'
```

Components are being sync correctly, but second one is returning error.

**Comment by marckraw** [comment]
After investigation: this is happening, because from @storyblok-components repo, we are deploying `src` and `dist` folder, and inside both of them, there is `.sb.js` files. Need to decide how to difrentiate it, or not copy `.sb.js` files to dist.

Also there will be a problem, when user will choose `--copy` option of `sb-mig add components` command. Because component will be inside `node_modules` still, for versioning and updating purposes.

**Comment by marckraw** [comment]
It will be nice to create some "manifest" of, where components live and how they should behave, maybe `storyblok.config.js` is the right place to have that, that way it will be still easy to define, and `sb-mig sync` will pick up from there: 
```
componentsDirectories: ["src", "storyblok", "node_modules/@other-scope", "node_modules/@storyblok-components"],
    scopedComponentsManifest: [
        {
            name: "ui-accordion",
            location: 'local',
            scope: '@other-scope'
        },
        {
            name: "ui-section",
            location: 'node_modules',
            scope: '@other-scope'
        },
        {
            name: "video-component",
            location: 'node_modules',
            scope: '@storyblok-components'
        },
        {
            name: "simple-text-block",
            location: 'local',
            scope: '@storyblok-components'
        }
    ]
```

**Comment by marckraw** [comment]
The reason behind this is, that if we have component inside `node_modules`, and we copy that with `sb-mig --copy` command, esentially, sb schema files will be in 3 locations: 
```
node_modules/src
node_modules/lib
local file system
```

so we need to infom `sb-mig sync` where provided component should have `sb.js` schema files. Because we still want to have fallback of other places.

**Comment by marckraw** [comment]
Issue is partially resolved, in scope component boilerplate there will be no copy command for schemes - so it will only be in src folder. Src folder is exposed to npm anyway, so there will be direct access to schema files to import.
